### ISSUE TITLE
Support for dnsjava 3

### ISSUE THREAD

**Issue by mwullink** [ibauersachs/dnssecjava#23]
dnssecjava is not compatible with the changed api of dnsjavva 3

it results in the following error.

java.lang.NoSuchMethodError: 'org.xbill.DNS.RRset[] org.xbill.DNS.Message.getSectionRRsets(int)'
	at org.jitsi.dnssec.SMessage.<init>(SMessage.java:114)
	at org.jitsi.dnssec.validator.ValidatingResolver.sendRequest(ValidatingResolver.java:675)
	at org.jitsi.dnssec.validator.ValidatingResolver.send(ValidatingResolver.java:1219)

**Comment by ibauersachs** [comment]
Thanks, I'm already working on that. Unfortunately Mockito/Powermock seems to have a bug/"feature" that I'm now running into and makes the unit tests fail.
